# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
